export const GET_CUSTOMER_LIST = 'customer/GET_CUSTOMER_LIST';
export const UPDATE_PAGE_SORT_CUSTOMER_LIST = 'customer/UPDATE_PAGE_SORT_CUSTOMER_LIST';
export const UPDATE_CUSTOMER_STATUS = 'customer/UPDATE_CUSTOMER_STATUS';
export const UPDATE_CUSTOMER_LIST_STATUS = 'customer/UPDATE_CUSTOMER_LIST_STATUS';