export const GET_CUSTOMER = 'account/GET_CUSTOMER';
export const GET_ADDRESS_CUSTOMER = 'account/GET_ADDRESS_CUSTOMER';
export const GET_IDENTIFY_DOCS_CUSTOMER = 'account/GET_IDENTIFY_DOCS_CUSTOMER';
