export const GET_CUSTOMER = 'customer/GET_CUSTOMER';
export const GET_ADDRESS_CUSTOMER = 'customer/GET_ADDRESS_CUSTOMER';
export const GET_IDENTIFY_DOCS_CUSTOMER = 'customer/GET_IDENTIFY_DOCS_CUSTOMER';
export const UPDATE_CUSTOMER = 'customer/UPDATE_CUSTOMER';