export const GET_ROLE_DETAIL = 'roleDetail/GET_ROLE_DETAIL';
export const GET_ROLE_PERMISSION_DETAIL = 'roleDetail/GET_ROLE_PERMISSION_DETAIL';
export const UPDATE_PAGE_SORT_ROLE_PERMISSION_LIST = 'roleDetail/UPDATE_PAGE_SORT_ROLE_PERMISSION_LIST';
export const GET_ALL_PERMISSION = 'roleDetail/GET_ALL_PERMISSION';
