export const GET_ACCOUNT_LIST = 'account/GET_ACCOUNT_LIST';
export const UPDATE_PAGE_SORT_ACCOUNT_LIST = 'account/UPDATE_PAGE_SORT_ACCOUNT_LIST';
export const UPDATE_ACCOUNT_STATUS = 'account/UPDATE_ACCOUNT_STATUS';
export const UPDATE_ACCOUNT_LIST_STATUS = 'account/UPDATE_ACCOUNT_LIST_STATUS';